[package]
name = "lipl-api-client"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
lipl-core = { path = "../../../lipl-repo-rest/crates/lipl-core", default-features = false, features = ["reqwest"] }
json-api-client = { path = "../json-api-client" }
futures-util = "0.3.25"

[dev-dependencies]
tokio = { version = "1.23", features = ["rt", "macros"] }
