[package]
edition.workspace = true
name = "lipl-api-client"
rust-version.workspace = true
version.workspace = true

[dependencies]
async-trait = "0.1"
lipl-core = { path = "../../../lipl-storage/crates/lipl-core", default-features = false }
rest-json-client = { path = "../rest-json-client" }
futures-util = "0.3"

[dev-dependencies]
tokio = { version = "1.23", features = ["rt", "macros"] }
