[package]
name = "json_api_client"
version = "0.1.0"
edition = "2021"

[dependencies]
lipl-core = { path = "../lipl/crates/lipl-core" }
reqwest = { version = "0.11", features = ["json", "gzip"] }
thiserror = "1.0.38"

[dev-dependencies]
tokio = { version = "1.23", features = ["macros", "rt"] }
