[package]
name = "placeholder"
authors.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
serde = { version = "1.0.188", features = ["derive"] }
serde_with = "3.3.0"
